services:
  mysql-rower:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=rower
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - '3307:3306'
    volumes:
      - ./mysql-book/data:/var/lib/mysql
      - ./mysql-book/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h",
              "localhost", "-pmysql" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    depends_on:
      mysql-rower:
        condition: service_healthy
    expose:
      - "8080"

#  app2:
#    build: .
#    depends_on:
#      - mysql-rower
#    expose:
#      - "8080"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      mysql-rower:
        condition: service_healthy
